### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by davidsneighbour** [sandoche/CuratedStack-nocode-template#41]
Trying the local development route fails when running `npm install`. Deploying directly on Netlify stops at the same point. It also throws plenty of deprecation errors. Simply updating all dependencies blindly (`npm-check-updates -u`) leads to installability, but then npm run build fails.

npm version:

```
{
  'curatedstack-nocode-template': '1.0.0',
  npm: '8.3.0',
  node: '16.8.0',
  v8: '9.2.230.21-node.20',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

Log is attached
deleted

**Comment by sandoche** [comment]
The repository is missing its .nvmrc

I invite you to try again using node js 14.x with nvm or n

**Comment by davidsneighbour** [comment]
using node v14 works. thanks.
